# Hajimi configuration file.
# This is a basic example.
# Replace the following contents with your own settings.

port: 7890
# HTTP proxy port

socks-port: 7891
# SOCKS5 proxy port

allow-lan: false
# Allow other devices on your LAN to connect to Clash.

mode: rule
# Clash operating mode: rule, global, or direct.

log-level: info
# Log output level: silent, error, warning, info, debug.

external-controller: '127.0.0.1:9090'
# Address and port for external dashboard control.

secret: ''
# Password for external dashboard access.

---

proxies:
  # List of your proxy server configurations.

  - name: "Node 1"
    type: ss
    server: "your_server_ip_1"
    port: 443
    cipher: "aes-256-gcm"
    password: "your_password_1"
    udp: true

  - name: "Node 2"
    type: vmess
    server: "your_server_domain_2"
    port: 8080
    uuid: "your_uuid_2"
    alterId: 0
    cipher: "auto"
    network: ws
    ws-path: "/your/path"
    udp: true

---

proxy-groups:
  # Groups for organizing and managing proxies.

  - name: "Manual Select"
    type: select
    proxies:
      - "Node 1"
      - "Node 2"
      - "DIRECT"

  - name: "Auto Select"
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - "Node 1"
      - "Node 2"

---

rules:
  # Traffic routing rules. Matched from top to bottom.

  - DOMAIN-SUFFIX,google.com,Auto Select
  - DOMAIN-SUFFIX,youtube.com,Auto Select
  - GEOIP,CN,DIRECT
  - MATCH,Manual Select
